# Generated by Django 3.1.4 on 2020-12-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinShake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('proteinPercentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='g of Protein per 100g')),
                ('creaminess', models.SmallIntegerField(verbose_name='Creaminess')),
                ('solubility', models.SmallIntegerField(verbose_name='Solubility')),
                ('sweetness', models.SmallIntegerField(verbose_name='Sweetness')),
                ('artificiality', models.SmallIntegerField(verbose_name='Artificiality')),
                ('smell', models.SmallIntegerField(verbose_name='Smell')),
                ('taste', models.SmallIntegerField(verbose_name='Taste')),
                ('opinion', models.SmallIntegerField(verbose_name='Personal Opinion')),
            ],
        ),
    ]
