# Generated by Django 3.1.4 on 2020-12-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinshake',
            name='review',
            field=models.TextField(default='', verbose_name='Review'),
            preserve_default=False,
        ),
    ]
