# Generated by Django 3.1.4 on 2020-12-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_proteinshake_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinshake',
            name='url',
            field=models.URLField(default='', verbose_name='Product Page'),
            preserve_default=False,
        ),
    ]
